# Generated by Django 4.0.5 on 2022-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo_models',
            name='contact_no',
            field=models.BigIntegerField(),
        ),
    ]
